- {id: administrative-enheter-norge-utm-33-hele-landet, link: /download/content/administrative-enheter-norge-utm-33-hele-landet,
  name: 'Administrative enheter Norge, UTM 33, hele landet'}
- {id: administrative-enheter-norge-wgs-84-hele-landet-geojson, link: /download/content/administrative-enheter-norge-wgs-84-hele-landet-geojson,
  name: 'Administrative enheter Norge, WGS 84, hele landet, geoJSON'}
- {id: administrative-fylker-utm-33-fylkesinndeling, link: /download/content/administrative-fylker-utm-33-fylkesinndeling,
  name: 'Administrative fylker, UTM 33, fylkesinndeling'}
- {id: administrative-kommuner-utm-33-fylkesinndeling, link: /download/content/administrative-kommuner-utm-33-fylkesinndeling,
  name: 'Administrative kommuner, UTM 33, fylkesinndeling'}
- {id: digitale-postnummergrenser-utm33-shape-hele-landet, link: /download/content/digitale-postnummergrenser-utm33-shape-hele-landet,
  name: 'Digitale postnummergrenser, UTM33, Shape, Hele landet'}
- {id: digitale-postnummergrenser-utm33-sosi-hele-landet, link: /download/content/digitale-postnummergrenser-utm33-sosi-hele-landet,
  name: 'Digitale postnummergrenser, UTM33, SOSI, Hele landet'}
- {id: dybdedata-utm33-shape-format, link: /download/content/dybdedata-utm33-shape-format,
  name: 'Dybdedata, UTM33, SHAPE format'}
- {id: dybdedata-utm33-sosi-format, link: /download/content/dybdedata-utm33-sosi-format,
  name: 'Dybdedata, UTM33, SOSI format'}
- {id: elveg-adresser-utm-33-hele-landet, link: /download/content/elveg-adresser-utm-33-hele-landet,
  name: 'Elveg, Adresser, UTM 33, Hele landet'}
- {id: elveg-geometri-utm-33-hele-landet, link: /download/content/elveg-geometri-utm-33-hele-landet,
  name: 'Elveg, Geometri UTM 33, Hele landet'}
- {id: geodesidata-altimetri-wgs84-textdat-filer, link: /download/content/geodesidata-altimetri-wgs84-textdat-filer,
  name: 'Geodesidata, Altimetri, WGS84, TEXT/DAT filer'}
- {id: geodesidata-geoide-wgs84-textdat-filer, link: /download/content/geodesidata-geoide-wgs84-textdat-filer,
  name: 'Geodesidata, Geoide, WGS84, TEXT/DAT filer'}
- {id: geodesidata-hastighetsfelt-norge-itrf2008-textdat-filer, link: /download/content/geodesidata-hastighetsfelt-norge-itrf2008-textdat-filer,
  name: 'Geodesidata, Hastighetsfelt for Norge, ITRF2008, TEXT/DAT filer'}
- {id: n2000-kartdata-utm-33-hele-landet, link: /download/content/n2000-kartdata-utm-33-hele-landet,
  name: 'N2000 Kartdata, UTM 33, hele landet'}
- {id: n2000-kartdata-utm33-hele-landet-fgdb, link: /download/content/n2000-kartdata-utm33-hele-landet-fgdb,
  name: 'N2000 Kartdata, UTM33, hele landet, FGDB'}
- {id: n2000-kartdata-utm33-hele-landet-postgis, link: /download/content/n2000-kartdata-utm33-hele-landet-postgis,
  name: 'N2000 Kartdata, UTM33, hele landet, PostGIS'}
- {id: n50-kartdata-utm-33-kommunevis-inndeling, link: /download/content/n50-kartdata-utm-33-kommunevis-inndeling,
  name: 'N50 Kartdata, UTM 33, kommunevis inndeling'}
- {id: n50-kartdata-utm33-hele-landet-fgdb, link: /download/content/n50-kartdata-utm33-hele-landet-fgdb,
  name: 'N50 Kartdata, UTM33, hele landet, FGDB'}
- {id: n50-kartdata-utm33-hele-landet-postgis, link: /download/content/n50-kartdata-utm33-hele-landet-postgis,
  name: 'N50 Kartdata, UTM33, hele landet, PostGIS'}
- {id: nasjonal-database-tur-og-friluftsruter-postgis, link: /download/content/nasjonal-database-tur-og-friluftsruter-postgis,
  name: 'Nasjonal database for tur- og friluftsruter, PostGIS'}
- {id: nasjonal-database-tur-og-friluftsruter-sosi, link: /download/content/nasjonal-database-tur-og-friluftsruter-sosi,
  name: 'Nasjonal database for tur- og friluftsruter, SOSI'}
- {id: norges-maritime-grenser-geografiske-koordinater, link: /download/content/norges-maritime-grenser-geografiske-koordinater,
  name: 'Norges maritime grenser, Geografiske koordinater'}
- {id: offisielle-adresser-utm33-csv, link: /download/content/offisielle-adresser-utm33-csv,
  name: 'Offisielle adresser, UTM33, CSV'}
- {id: offisielle-adresser-utm33-sosi, link: /download/content/offisielle-adresser-utm33-sosi,
  name: 'Offisielle adresser, UTM33, SOSI '}
- {id: sj%C3%B8-dybdekurver-utm33-1000m-grid-s57, link: /download/content/sj%C3%B8-dybdekurver-utm33-1000m-grid-s57,
  name: 'Sjø dybdekurver, UTM33, 1000m grid, S57'}
- {id: sj%C3%B8-dybdekurver-utm33-1000m-grid-sosi, link: /download/content/sj%C3%B8-dybdekurver-utm33-1000m-grid-sosi,
  name: 'Sjø dybdekurver, UTM33, 1000m grid, SOSI'}
- {id: sj%C3%B8-dybdekurver-utm33-600m-grid-shape, link: /download/content/sj%C3%B8-dybdekurver-utm33-600m-grid-shape,
  name: 'Sjø dybdekurver, UTM33, 600m grid, Shape'}
- {id: sj%C3%B8-terrengmodell-25m-utm33, link: /download/content/sj%C3%B8-terrengmodell-25m-utm33,
  name: 'Sjø terrengmodell 25m, UTM33'}
- {id: sj%C3%B8-terrengmodell-50m-utm33, link: /download/content/sj%C3%B8-terrengmodell-50m-utm33,
  name: 'Sjø terrengmodell 50m, UTM33'}
- {id: sj%C3%B8-terrengmodell-5m-utm33, link: /download/content/sj%C3%B8-terrengmodell-5m-utm33,
  name: 'Sjø terrengmodell 5m, UTM33'}
- {id: statistiske-enheter-grunnkretser-utm-33-hele-landet, link: /download/content/statistiske-enheter-grunnkretser-utm-33-hele-landet,
  name: 'Statistiske enheter Grunnkretser, UTM 33, hele landet'}
- {id: stedsnavn-ssr-sosi-utm33, link: /download/content/stedsnavn-ssr-sosi-utm33,
  name: Stedsnavn SSR SOSI UTM33}
- {id: stedsnavn-ssr-wgs84-geojson, link: /download/content/stedsnavn-ssr-wgs84-geojson,
  name: 'Stedsnavn SSR, WGS84, geoJSON'}
- {id: valgkretser-lokale-soner-kommunevis-hele-landet-sosi, link: /download/content/valgkretser-lokale-soner-kommunevis-hele-landet-sosi,
  name: 'Valgkretser, lokale soner, kommunevis for hele landet, SOSI'}
- {id: vbase-utm-33, link: /download/content/vbase-utm-33, name: 'Vbase, UTM 33'}
- {id: vbase-utm-33-fylkesinndeling, link: /download/content/vbase-utm-33-fylkesinndeling,
  name: 'Vbase, UTM 33 fylkesinndeling'}
